---
title: "MSDS 6372. Bank Data (Should be changed before submission!!!)"
output: 
  pdf_document
author: Swee Chew, Rene Pineda Alvarenga, Volodymyr Orlov
header-includes:
   - \usepackage{amsmath}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggpubr)
library(car)
```

## Introduction

While telemarketing might be considered as a cornerstone of modern advertising strategies by some companies, its role is highly questionable and sometimes it is viewed as a total waste of resources by others^[https://www.prospectresearch.co.uk/blog/telemarketing-still-effective/]. Here we attempt to analize affect of telemarketing on attracting new clients in a finance industry by looking at the success of telemarketing calls for selling bank long-term
deposits recorded by a Portuguese retail bank. We apply multiple statistical methods and analyze outcomes of two separate models:

1. (objective 1 model title!!!). We found that ...
1. (objective 2 model title!!!). We found that ...

## Data Description

The data is related with direct marketing campaigns of a Portuguese banking institution. The marketing campaigns were based on phone calls. Often, more than one contact to the same client was required, in order to access if the product (bank term deposit) would be ('yes') or not ('no') subscribed. 

## Exploratory Analysis

TBD

## Objective 1 (Should be changed before submission!!!)
 TBD

## Objective 2 (Should be changed before submission!!!)

 

## Code

All code used to generate models, plots and report related to this work can be found in [https://github.com/VolodymyrOrlov/MSDS6372_Project2](https://github.com/VolodymyrOrlov/MSDS6372_Project2)

## Figures and Tables

TBD



